[package]
name = "needle-core"
version = "0.1.13"
edition = "2021"
license = "GPL-2.0-only"

[dependencies]
bytemuck = "1.20.0"
chrono = "0.4.38"
directories = "6.0.0"
env_logger = "0.11.5"
glyphon = "0.9.0"
log = "0.4.22"
pollster = "0.4.0"
serde = {version = "1.0.215", features = ["derive"]}
thiserror = "2.0.12"
toml = "0.8.19"
wgpu = "25.0.0"
winit = { version = "0.30" }
